url: ""
baseurl: "impact-website"

# Site settings
title: impact++
email: udubimpact@gmail.com
description: "Welcome to the official website of the UW Impact++. Click here if you want to increment your impact!"


# Team names, titles and social links
people:
- name: Shourya Jain
  pic: shourya
  position: Founder/President
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/shourjain/

- name: Samantha Ballata
  pic: samantha
  position: Operations Manager
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/samantha-ballata-2804b6168/

- name: Ofek Inbar
  pic: ofek
  position: Project Lead
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/ofek-inbar/

- name: Jenny Cho
  pic: jenny
  position: Officer
  social:
  - title: linkedin
    url: https://www.linkedin.com/in/yeonjinc/

- name: Deepanshu Gupta
  pic: deepanshu
  position: Student Lead
  social:
  - title: linkedin
    url: https://www.linkedin.com/in/guptad2/

- name: Frankie O'Rourke
  pic: frankie
  position: Lead Developer
  social:
  - title: linkedin
    url: https://www.linkedin.com/in/frankie-o/
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  #- title: twitter
    #url: http://twitter.com/jekyllrb

# Postal address (add as many lines as necessary)
address:
  - line: 185 E Stevens Way NE
  - line: Seattle, WA 98195

# Build settings
markdown: kramdown
permalink: pretty
